# Generated by Django 4.1.5 on 2023-01-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("post_code", models.CharField(max_length=10)),
                ("street", models.CharField(max_length=100)),
                ("street_number", models.PositiveIntegerField(blank=True, null=True)),
                ("phone", models.PositiveIntegerField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, default="Open hours coming soon... ", null=True
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
