# Generated by Django 4.1.5 on 2023-01-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0002_rental_open_hours_alter_rental_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
