# Generated by Django 4.1.5 on 2023-01-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0003_alter_rental_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental",
            name="description",
            field=models.TextField(
                default="Description coming soon... ", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="rental",
            name="open_hours",
            field=models.TextField(default="Open hours coming soon... "),
        ),
    ]
