# Generated by Django 4.1.5 on 2023-01-06 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cars", "0001_initial"),
        ("rentals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="renthistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="carType",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cars.cartypes"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="rentals",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rentals.rental"
            ),
        ),
    ]
